name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt6
        pip install pywin32
    
    - name: Install UPX
      run: |
        $url = "https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-win64.zip"
        Invoke-WebRequest -Uri $url -OutFile upx.zip
        Expand-Archive upx.zip -DestinationPath .
        Move-Item upx-4.2.1-win64/upx.exe "C:\Program Files\UPX\upx.exe" -Force
      
    - name: Build with PyInstaller
      run: |
        pyinstaller window_manager.spec
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: window_manager
        path: dist/window_manager.exe

    - name: Upload to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/window_manager.exe
        asset_name: window_manager.exe
        asset_content_type: application/octet-stream